# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_auto_20150621_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='cardlist',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='cardlistgroup',
            name='mode',
            field=models.CharField(choices=[('r', 'read'), ('cr', 'create and read'), ('crud', 'create, read, update and delete')], default='r', max_length=4),
        ),
        migrations.AlterField(
            model_name='cardlistuser',
            name='mode',
            field=models.CharField(choices=[('r', 'Read'), ('cr', 'Read, Create'), ('crud', 'Full')], default='r', max_length=4),
        ),
        migrations.AlterField(
            model_name='sharecardlist',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
