# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0003_auto_20150104_1943'),
        ('usermgmt', '0004_auto_20150103_1740'),
    ]

    operations = [
    ]
