# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0005_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservalidationcode',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
